site_name: TIJ
nav:
    - Home: index.md
    - About: 
      - Vision: about.md
      - Mission: mission.md
    - Service: service.md
    - Gallery: gallary.md
    - Contact Us: contact.md
theme:
   name: mkdocs
   custom_dir: custom_theme/
extra_css: [extra.css]

